### ISSUE TITLE
Unit/Machine/Unit-Files Broken if fleet version changes

### ISSUE THREAD

**Issue by rosskukulinski** [yodlr/CoreGI#17]
```
Mar 31 18:48:25 prod-coreos-b-dfw-02 docker[3202]: [2015-03-31T18:48:25.841Z] ERROR: coregi/14 on XXXX: Error - Fleetctl: listUnitFiles
Mar 31 18:48:25 prod-coreos-b-dfw-02 docker[3202]:     Error: ####################################################################
Mar 31 18:48:25 prod-coreos-b-dfw-02 docker[3202]: WARNING: fleetctl (0.9.0+git) is older than the latest registered
Mar 31 18:48:25 prod-coreos-b-dfw-02 docker[3202]: version of fleet found in the cluster (0.9.1). You are strongly
Mar 31 18:48:25 prod-coreos-b-dfw-02 docker[3202]: recommended to upgrade fleetctl to prevent incompatibility issues.
Mar 31 18:48:25 prod-coreos-b-dfw-02 docker[3202]: ####################################################################
Mar 31 18:48:25 prod-coreos-b-dfw-02 docker[3202]: at /src/node_modules/fleetctl/lib/executor.js:9:27
Mar 31 18:48:25 prod-coreos-b-dfw-02 docker[3202]: at ChildProcess.exithandler (child_process.js:646:7)
Mar 31 18:48:25 prod-coreos-b-dfw-02 docker[3202]: at ChildProcess.emit (events.js:98:17)
Mar 31 18:48:25 prod-coreos-b-dfw-02 docker[3202]: at maybeClose (child_process.js:756:16)
Mar 31 18:48:25 prod-coreos-b-dfw-02 docker[3202]: at Process.ChildProcess._handle.onexit (child_process.js:823:5)
```

**Comment by rosskukulinski** [comment]
I think we should submit a PR to normanjoyner/node-fleetctl to ignore this error/warning

**Comment by rosskukulinski** [comment]
Attempted fix in 48ae12af134d42be692e461e0fd9620a78ed728e via https://github.com/yodlr/node-fleetctl/commit/6aba29d1c633e8175015bb24def89bea9f17854b

**Comment by rosskukulinski** [comment]
Upstream has been PRd in https://github.com/normanjoyner/node-fleetctl/pull/12
